CFLAGS=-std=gnu89 -ggdb -O2 -Wall -Wextra -Wpedantic -Werror

default:
	gcc $(CFLAGS) -o day1part1 ./day1part1.c
	gcc $(CFLAGS) -o day1part2 ./day1part2.c -lehht

clean:
	rm *.o *.~ day1part1 day1part2
